### ISSUE TITLE
是否可以直接提供一个 可以执行的 pipeline

### ISSUE THREAD

**Issue by ChunelFeng** [Alwaysssssss/nndeploy#4]
比如，不需要 自己cp  config.cmake 做修改，也不用 clone 内容到本地，
本地放一张图片和一个小模型，可以一个shell 跑起来？

或者，可以一个shell 拉取下来 模型和图片？不需要在 clone了

**Comment by Alwaysssssss** [comment]
采取了第二种方式，并按照你上次编译运行的体验重新修改并整理README.md文档
